# render.yaml - Versión actualizada con dependencias del sistema

services:
  # 1. El servicio web: ligero y rápido, solo gestiona la API.
  - type: web
    name: api-videos-ia
    env: python
    plan: free
    region: oregon

    buildCommand: |
      # Comandos para instalar dependencias del sistema operativo
      apt-get update && apt-get install -y imagemagick ffmpeg # <-- ¡LÍNEAS AÑADIDAS!
      # Comandos para instalar dependencias de Python
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "gunicorn app:app"

    envVars:
      - key: GCS_BUCKET_NAME
        value: "nombre-de-tu-bucket-en-gcs"
      - key: GCS_CREDENTIALS_JSON
        fromSecret: true
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: cola-de-renderizado
          property: connectionString

  # 2. El trabajador: dedicado 100% a procesar videos.
  - type: worker
    name: worker-renderizador-videos
    env: python
    plan: free

    buildCommand: |
      # Comandos para instalar dependencias del sistema operativo
      apt-get update && apt-get install -y imagemagick ffmpeg # <-- ¡LÍNEAS AÑADIDAS!
      # Comandos para instalar dependencias de Python
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "rq worker -u $REDIS_URL default"

    envVars:
      - key: GCS_BUCKET_NAME
        value: "nombre-de-tu-bucket-en-gcs"
      - key: GCS_CREDENTIALS_JSON
        fromSecret: true
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: cola-de-renderizado
          property: connectionString

addons:
  - name: cola-de-renderizado
    plan: free

