# render.yaml
services:
  - type: web
    name: backend-render-videos
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py" # Asegúrate de que tu archivo principal se llama app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # <--- ¡Cambiado aquí! O 3.10.1, 3.10.X, la versión que quieras usar
      - key: PORT
        value: 5002
