# render.yaml - Versión a prueba de fallos

services:
  - type: web
    name: renderizador-inteligente-ia
    env: python
    plan: free
    region: oregon
    healthCheckPath: /

    buildCommand: |
      apt-get update && apt-get install -y ffmpeg imagemagick
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "gunicorn --workers 3 --threads 3 --timeout 120 app:app"
