services:
  - type: web
    name: renderizador-ia
    env: python
    plan: free  # Puedes cambiar a 'starter' o superior si lo necesitas
    runtime: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # Agrega este valor desde el dashboard de Render
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: PORT
        value: 5001
