services:
  - type: web
    name: backend-render-videos
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    env: 
      PORT: 5002
