# render.yaml - Versión Final y Corregida

services:
  - type: web
    name: renderizador-inteligente-ia
    env: python
    plan: free
    region: oregon
    healthCheckPath: /
    
    # Aquí forzamos una versión de Python estable y compatible
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

    buildCommand: |
      apt-get update && apt-get install -y ffmpeg imagemagick
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "gunicorn --workers 3 --threads 3 --timeout 120 app:app"
