services:
  - type: web
    name: renderizador-ia
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install --no-cache-dir moviepy
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --workers 3 --threads 3 --timeout 180 app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: PORT
        value: 5001
