# render.yaml
services:
  - type: web
    name: video-render-backend
    env: python
    buildCommand: "pip install -r requirements.txt" # Instala las dependencias
    startCommand: "python your_app_name.py" # Inicia tu aplicaci칩n Flask
    ports:
      - 5002 # El puerto que tu aplicaci칩n Flask est치 usando

# Opcional: Si necesitas m치s recursos o un plan diferente
# plan: standard # developer | standard | pro | private

# Opcional: Variables de entorno si las necesitas (ej. API keys)
# envVars:
#   - key: MY_API_KEY
#     value: my_secret_value
