# render.yaml - Versión final v4.2 (Método de variable de entorno)

services:
  - type: web
    name: renderizador-inteligente-ia
    env: python
    plan: free
    region: oregon
    healthCheckPath: /

    buildCommand: |
      apt-get update && apt-get install -y ffmpeg imagemagick
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "gunicorn --workers 3 --threads 3 --timeout 120 app:app"

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      # Las siguientes variables DEBES crearlas en el Dashboard de Render
      # Asegúrate de marcarlas como "Secret" si contienen información sensible.
      - key: GOOGLE_API_KEY
        fromSecret: true
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      # Esta es la variable CLAVE que contendrá todo tu archivo JSON de credenciales
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        fromSecret: true
        
